# This is a global registry for public HSDP services
# containing most static configuration. Its main purpose is to 
# reduce configuration parameters and drive automation of the 
# platform further by having a human and machine readable source of
# common configuration parameters
# 
# Before using it as your source of truth please confirm it has
# the expected values.
#
# Also it goes without saying, but we will say it anyway:
# It is your responsibilty to ensure correct configuration of 
# your deployments.
#
# If you spot errors or incomplete information please raise a 
# PR. Thanks!
#
# Definitions:
#
# Region - a geographical region where services are deployed
# Environment - a stage within a geographical region to aid in phased deployment 
# Service - a consumable software service
# Instance - a specific deployment of a service
#
# Hierarchy example:
#
# Earth
#   Region us-east
#     Service
#       cf
#     Environment client-test
#       Service
#         iam
#	  idm
#         cartel
#     Environemnt production
#       Service
#         iam
#         idm
#         cartel
#         cdr
#       
#   Region eu-west
#     Environment client-test
#       Service
#         iam
#         idm
#         has
#     Environemnt production
#       Service
#         iam
#         idm
#         s3cred
# 
# Nesting syntax: [region.environment.service.instance]
#
# Services can be tied to a region or an environment
# We also anticipate global services at some point
# Example of a region bound service: Cloud foundry
# Example of a enivronment bound service: IAM

# Service Cloud foundry
[region.us-east.service.cf]
api_url = "https://api.cloud.pcftest.com"
[region.eu-west.service.cf]
api_url = "https://api.eu1.phsdp.com"
[region.sa1.service.cf]
api_url = "https://api.sys.sa1.hsdp.io"

# Service DOCKER-REGISTRY
[region.us-east.service.docker-registry]
host = "docker.na1.hsdp.io"
[region.eu-west.service.docker-registry]
host = "docker.eu1.hsdp.io"
[region.sa1.service.docker-registry]
host = "docker.sa1.hsdp.io"

# Service CONSOLE
[region.us-east.service.console]
url = "https://console.na1.hsdp.io"
[region.eu-west.service.console]
url = "https://console.eu1.hsdp.io"
[region.sa1.service.console]
url = "https://console.sa1.hsdp.io"

# Service IAM
[region.us-east.env.client-test.service.iam]
iam_url = "https://iam-client-test.us-east.philips-healthsuite.com"
idm_url = "https://idm-client-test.us-east.philips-healthsuite.com"
authui_url = "https://authui-client-test.us-east.philips-healthsuite.com"
oidc_configuration = "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[region.us-east.env.prod.service.iam]
iam_url = "https://iam-service.us-east.philips-healthsuite.com"
idm_url = "https://idm-service.us-east.philips-healthsuite.com"
authui_url = "https://authui-service.us-east.philips-healthsuite.com"
oidc_configuration = "https://iam-service.us-east.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[region.eu-west.env.client-test.service.iam]
iam_url = "https://iam-client-test.eu-west.philips-healthsuite.com"
idm_url = "https://idm-client-test.eu-west.philips-healthsuite.com"
authui_url = "https://authui-client-test.eu-west.philips-healthsuite.com"
oidc_configuration = "https://iam-client-test.eu-west.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[region.eu-west.env.prod.service.iam]
iam_url = "https://iam-service.eu-west.philips-healthsuite.com"
idm_url = "https://idm-service.eu-west.philips-healthsuite.com"
authui_url = "https://authui-service.eu-west.philips-healthsuite.com"
oidc_configuration = "https://iam-service.eu-west.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[region.sa1.env.client-test.service.iam]
iam_url = "https://iam-client-test.sa1.hsdp.io"
idm_url = "https://idm-client-test.sa1.hsdp.io"
authui_url = "https://authui-client-test.sa1.hsdp.io"
oidc_configuration = "https://iam-client-test.sa1.hsdp.io/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[region.sa1.env.prod.service.iam]
iam_url = "https://iam-service.sa1.hsdp.io"
idm_url = "https://idm-service.sa1.hsdp.io"
authui_url = "https://authui-service.sa1.hsdp.io"
oidc_configuration = "https://iam-service.sa1.hsdp.io/authorize/oauth2/.well-known/openid-configuration?api-version=1"

# Service CARTEL
[region.us-east.service.cartel]
host = "cartel-na1.cloud.phsdp.com"
[region.eu-west.service.cartel]
host = "cartel-eu1.cloud.phsdp.com"

# Service S3CREDS
[region.us-east.env.client-test.service.s3creds]
url = "https://s3creds-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.s3creds]
url = "https://s3creds-service.us-east.philips-healthsuite.com"
[region.eu-west.env.client-test.service.s3creds]
url = "https://s3creds-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.s3creds]
url = "https://s3creds-service.eu-west.philips-healthsuite.com"

# Service HAS
[region.eu-west.env.client-test.service.has]
url = "https://has-client-test.eu-west.philips-healthsuite.com"

# Service CDR-STU3
[region.us-east.env.sandbox.service.cdr-stu3]
url = "https://cdr-stu3-sandbox.us-east.philips-healthsuite.com"

# Service LOGGING
[region.eu-west.env.client-test.service.logging]
ingestor_url = "https://logingestor2-client-test.eu-west.philips-healthsuite.com"
kibana_url = "https://kibana-client-test.eu-west.philips-healthsuite.com"
[region.eu-west.env.prod.service.logging]
ingestor_url = "https://logingestor2.eu-west.philips-healthsuite.com"
kibana_url = "https://kibana.eu-west.philips-healthsuite.com"
[region.us-east.env.client-test.service.logging]
ingestor_url = "https://logingestor2-client-test.us-east.philips-healthsuite.com"
kibana_url = "https://kibana-client-test.us-east.philips-healthsuite.com"
[region.us-east.env.prod.service.logging]
ingestor_url = "https://logingestor2.us-east.philips-healthsuite.com"
kibana_url = "https://kibana.us-east.philips-healthsuite.com"
[region.sa1.env.client-test.service.logging]
ingestor_url = "https://logingestor2-client-test.sa1.hsdp.io"
kibana_url = "https://kibana-client-test.sa1.hsdp.io"
[region.sa1.env.prod.service.logging]
ingestor_url = "https://logingestor2.sa1.hsdp.io"
kibana_url = "https://kibana.sa1.hsdp.io"

