# This is a global registry for public HSDP services
# containing most static configuration. Its main purpose is to 
# reduce configuration parameters and drive automation of the 
# platform further by having a human and machine readable source of
# common configuration parameters
# 
# Before using it as your source of truth please confirm it has
# the expected values.
#
# Also it goes without saying, but we will say it anyway:
# It is your responsibilty to ensure correct configuration of 
# your deployments.
#
# If you spot errors or incomplete information please raise a 
# PR. Thanks!
#
# Definitions:
#
# Region - a geographical region where services are deployed
# Environment - a stage within a geographical region to aid in phased deployment 
# Service - a consumable software service
# Instance - a specific deployment of a service
#
# Hierarchy example:
#
# Earth
#   Region us-east
#     Service
#       cf
#     Environment client-test
#       Service
#         iam
#	  idm
#         cartel
#     Environemnt production
#       Service
#         iam
#         idm
#         cartel
#         cdr
#       
#   Region eu-west
#     Environment client-test
#       Service
#         iam
#         idm
#         has
#     Environemnt production
#       Service
#         iam
#         idm
#         s3cred
# 
# Nesting syntax: [region.environment.service.instance]
#
# Services can be tied to a region or an environment
# We also anticipate global services at some point
# Example of a region bound service: Cloud foundry
# Example of a enivronment bound service: IAM

# Service Cloud foundry
[reg.us-east.service.cf]
api_url = "https://api.cloud.pcftest.com"
[reg.eu-west.service.cf]
api_url = "https://api.eu1.phsdp.com"

# Environments
[reg.us-east.env.client-test]
[reg.us-east.env.prod]
[reg.eu-west.env.client-test]
[reg.eu-west.env.prod]

# Service IAM
[reg.us-east.env.client-test.service.iam]
base_url = "https://iam-client-test.us-east.philips-healthsuite.com"
oidc_configuration = "https://iam-client-test.us-east.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"
[reg.eu-west.env.client-test.service.iam]
base_url = "https://iam-client-test.eu-west.philips-healthsuite.com"
oidc_configuration = "https://iam-client-test.eu-west.philips-healthsuite.com/authorize/oauth2/.well-known/openid-configuration?api-version=1"

# Service IDM
[reg.us-east.env.client-test.service.idm]
base_url = "https://idm-client-test.us-east.philips-healthsuite.com"
[reg.eu-west.env.client-test.service.idm]
base_url = "https://idm-client-test.eu-west.philips-healthsuite.com"
[reg.us-east.env.prod.service.idm]
base_url = "https://idm-service.us-east.philips-healthsuite.com"
[reg.eu-west.env.prod.service.idm]
base_url = "https://idm-service.eu-west.philips-healthsuite.com"

# Service CARTEL
[reg.us-east.service.cartel]
host = "cartel-na1.cloud.phsdp.com"

# Service S3CREDS
[reg.us-east.env.client-test.service.s3creds]
base_url = "https://s3creds-client-test.us-east.philips-healthsuite.com"

# Service HAS
[reg.eu-west.env.client-test.service.has]
base_url = "https://has-client-test.eu-west.philips-healthsuite.com"
